const recipeLevel = [
    {
        "LEVEL": 1,
        "RLVL": 1,
        "STARS": 0,
        "CRAFTS": 22,
        "CONTROL": 11,
        "PROGRESS": 19,
        "QUALITY": 312,
        "DURABILITY": 60,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 2,
        "RLVL": 2,
        "STARS": 0,
        "CRAFTS": 22,
        "CONTROL": 11,
        "PROGRESS": 20,
        "QUALITY": 325,
        "DURABILITY": 60,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 3,
        "RLVL": 3,
        "STARS": 0,
        "CRAFTS": 22,
        "CONTROL": 11,
        "PROGRESS": 20,
        "QUALITY": 339,
        "DURABILITY": 60,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 4,
        "RLVL": 4,
        "STARS": 0,
        "CRAFTS": 22,
        "CONTROL": 11,
        "PROGRESS": 21,
        "QUALITY": 352,
        "DURABILITY": 60,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 5,
        "RLVL": 5,
        "STARS": 0,
        "CRAFTS": 50,
        "CONTROL": 25,
        "PROGRESS": 33,
        "QUALITY": 451,
        "DURABILITY": 60,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 6,
        "RLVL": 6,
        "STARS": 0,
        "CRAFTS": 50,
        "CONTROL": 25,
        "PROGRESS": 36,
        "QUALITY": 474,
        "DURABILITY": 60,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 7,
        "RLVL": 7,
        "STARS": 0,
        "CRAFTS": 50,
        "CONTROL": 25,
        "PROGRESS": 37,
        "QUALITY": 492,
        "DURABILITY": 60,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 8,
        "RLVL": 8,
        "STARS": 0,
        "CRAFTS": 59,
        "CONTROL": 29,
        "PROGRESS": 41,
        "QUALITY": 526,
        "DURABILITY": 60,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 9,
        "RLVL": 9,
        "STARS": 0,
        "CRAFTS": 59,
        "CONTROL": 29,
        "PROGRESS": 42,
        "QUALITY": 545,
        "DURABILITY": 60,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 10,
        "RLVL": 10,
        "STARS": 0,
        "CRAFTS": 59,
        "CONTROL": 29,
        "PROGRESS": 45,
        "QUALITY": 629,
        "DURABILITY": 60,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 11,
        "RLVL": 11,
        "STARS": 0,
        "CRAFTS": 67,
        "CONTROL": 33,
        "PROGRESS": 48,
        "QUALITY": 665,
        "DURABILITY": 60,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 12,
        "RLVL": 12,
        "STARS": 0,
        "CRAFTS": 67,
        "CONTROL": 33,
        "PROGRESS": 53,
        "QUALITY": 702,
        "DURABILITY": 60,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 13,
        "RLVL": 13,
        "STARS": 0,
        "CRAFTS": 67,
        "CONTROL": 33,
        "PROGRESS": 54,
        "QUALITY": 726,
        "DURABILITY": 60,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 14,
        "RLVL": 14,
        "STARS": 0,
        "CRAFTS": 67,
        "CONTROL": 33,
        "PROGRESS": 54,
        "QUALITY": 751,
        "DURABILITY": 60,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 15,
        "RLVL": 15,
        "STARS": 0,
        "CRAFTS": 67,
        "CONTROL": 33,
        "PROGRESS": 55,
        "QUALITY": 807,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 16,
        "RLVL": 16,
        "STARS": 0,
        "CRAFTS": 78,
        "CONTROL": 39,
        "PROGRESS": 63,
        "QUALITY": 866,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 17,
        "RLVL": 17,
        "STARS": 0,
        "CRAFTS": 78,
        "CONTROL": 39,
        "PROGRESS": 66,
        "QUALITY": 898,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 18,
        "RLVL": 18,
        "STARS": 0,
        "CRAFTS": 78,
        "CONTROL": 39,
        "PROGRESS": 67,
        "QUALITY": 939,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 19,
        "RLVL": 19,
        "STARS": 0,
        "CRAFTS": 82,
        "CONTROL": 41,
        "PROGRESS": 68,
        "QUALITY": 982,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 20,
        "RLVL": 20,
        "STARS": 0,
        "CRAFTS": 94,
        "CONTROL": 47,
        "PROGRESS": 74,
        "QUALITY": 1053,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 21,
        "RLVL": 21,
        "STARS": 0,
        "CRAFTS": 94,
        "CONTROL": 47,
        "PROGRESS": 75,
        "QUALITY": 1090,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 22,
        "RLVL": 22,
        "STARS": 0,
        "CRAFTS": 94,
        "CONTROL": 47,
        "PROGRESS": 75,
        "QUALITY": 1122,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 23,
        "RLVL": 23,
        "STARS": 0,
        "CRAFTS": 99,
        "CONTROL": 49,
        "PROGRESS": 79,
        "QUALITY": 1169,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 24,
        "RLVL": 24,
        "STARS": 0,
        "CRAFTS": 99,
        "CONTROL": 49,
        "PROGRESS": 85,
        "QUALITY": 1239,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 25,
        "RLVL": 25,
        "STARS": 0,
        "CRAFTS": 99,
        "CONTROL": 49,
        "PROGRESS": 89,
        "QUALITY": 1296,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 26,
        "RLVL": 26,
        "STARS": 0,
        "CRAFTS": 99,
        "CONTROL": 49,
        "PROGRESS": 90,
        "QUALITY": 1332,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 27,
        "RLVL": 27,
        "STARS": 0,
        "CRAFTS": 99,
        "CONTROL": 49,
        "PROGRESS": 91,
        "QUALITY": 1368,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 28,
        "RLVL": 28,
        "STARS": 0,
        "CRAFTS": 106,
        "CONTROL": 53,
        "PROGRESS": 100,
        "QUALITY": 1498,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 29,
        "RLVL": 29,
        "STARS": 0,
        "CRAFTS": 106,
        "CONTROL": 53,
        "PROGRESS": 101,
        "QUALITY": 1544,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 30,
        "RLVL": 30,
        "STARS": 0,
        "CRAFTS": 106,
        "CONTROL": 53,
        "PROGRESS": 102,
        "QUALITY": 1584,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 31,
        "RLVL": 31,
        "STARS": 0,
        "CRAFTS": 121,
        "CONTROL": 60,
        "PROGRESS": 106,
        "QUALITY": 1670,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 32,
        "RLVL": 32,
        "STARS": 0,
        "CRAFTS": 121,
        "CONTROL": 60,
        "PROGRESS": 110,
        "QUALITY": 1697,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 33,
        "RLVL": 33,
        "STARS": 0,
        "CRAFTS": 121,
        "CONTROL": 60,
        "PROGRESS": 111,
        "QUALITY": 1757,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 34,
        "RLVL": 34,
        "STARS": 0,
        "CRAFTS": 129,
        "CONTROL": 64,
        "PROGRESS": 115,
        "QUALITY": 1811,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 35,
        "RLVL": 35,
        "STARS": 0,
        "CRAFTS": 129,
        "CONTROL": 64,
        "PROGRESS": 123,
        "QUALITY": 1853,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 36,
        "RLVL": 36,
        "STARS": 0,
        "CRAFTS": 129,
        "CONTROL": 64,
        "PROGRESS": 124,
        "QUALITY": 1882,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 37,
        "RLVL": 37,
        "STARS": 0,
        "CRAFTS": 129,
        "CONTROL": 64,
        "PROGRESS": 128,
        "QUALITY": 1905,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 38,
        "RLVL": 38,
        "STARS": 0,
        "CRAFTS": 129,
        "CONTROL": 64,
        "PROGRESS": 129,
        "QUALITY": 1961,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 39,
        "RLVL": 39,
        "STARS": 0,
        "CRAFTS": 136,
        "CONTROL": 68,
        "PROGRESS": 137,
        "QUALITY": 2026,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 40,
        "RLVL": 40,
        "STARS": 0,
        "CRAFTS": 136,
        "CONTROL": 68,
        "PROGRESS": 138,
        "QUALITY": 2050,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 41,
        "RLVL": 41,
        "STARS": 0,
        "CRAFTS": 136,
        "CONTROL": 68,
        "PROGRESS": 143,
        "QUALITY": 2109,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 42,
        "RLVL": 42,
        "STARS": 0,
        "CRAFTS": 150,
        "CONTROL": 75,
        "PROGRESS": 144,
        "QUALITY": 2147,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 43,
        "RLVL": 43,
        "STARS": 0,
        "CRAFTS": 150,
        "CONTROL": 75,
        "PROGRESS": 155,
        "QUALITY": 2251,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 44,
        "RLVL": 44,
        "STARS": 0,
        "CRAFTS": 150,
        "CONTROL": 75,
        "PROGRESS": 156,
        "QUALITY": 2277,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 45,
        "RLVL": 45,
        "STARS": 0,
        "CRAFTS": 150,
        "CONTROL": 75,
        "PROGRESS": 158,
        "QUALITY": 2309,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 46,
        "RLVL": 46,
        "STARS": 0,
        "CRAFTS": 150,
        "CONTROL": 75,
        "PROGRESS": 159,
        "QUALITY": 2372,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 47,
        "RLVL": 47,
        "STARS": 0,
        "CRAFTS": 161,
        "CONTROL": 80,
        "PROGRESS": 167,
        "QUALITY": 2421,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 48,
        "RLVL": 48,
        "STARS": 0,
        "CRAFTS": 161,
        "CONTROL": 80,
        "PROGRESS": 172,
        "QUALITY": 2524,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 49,
        "RLVL": 49,
        "STARS": 0,
        "CRAFTS": 161,
        "CONTROL": 80,
        "PROGRESS": 174,
        "QUALITY": 2551,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 50,
        "RLVL": 50,
        "STARS": 0,
        "CRAFTS": 176,
        "CONTROL": 88,
        "PROGRESS": 186,
        "QUALITY": 2641,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 50,
        "RLVL": 55,
        "STARS": 1,
        "CRAFTS": 325,
        "CONTROL": 325,
        "PROGRESS": 195,
        "QUALITY": 2646,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 50,
        "RLVL": 70,
        "STARS": 2,
        "CRAFTS": 325,
        "CONTROL": 325,
        "PROGRESS": 233,
        "QUALITY": 2921,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 50,
        "RLVL": 90,
        "STARS": 3,
        "CRAFTS": 391,
        "CONTROL": 374,
        "PROGRESS": 445,
        "QUALITY": 4980,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 50,
        "RLVL": 110,
        "STARS": 4,
        "CRAFTS": 451,
        "CONTROL": 407,
        "PROGRESS": 586,
        "QUALITY": 5783,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 51,
        "RLVL": 115,
        "STARS": 0,
        "CRAFTS": 468,
        "CONTROL": 426,
        "PROGRESS": 339,
        "QUALITY": 3951,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 52,
        "RLVL": 125,
        "STARS": 0,
        "CRAFTS": 502,
        "CONTROL": 462,
        "PROGRESS": 503,
        "QUALITY": 5172,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 53,
        "RLVL": 130,
        "STARS": 0,
        "CRAFTS": 519,
        "CONTROL": 480,
        "PROGRESS": 586,
        "QUALITY": 5783,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 54,
        "RLVL": 133,
        "STARS": 0,
        "CRAFTS": 529,
        "CONTROL": 491,
        "PROGRESS": 641,
        "QUALITY": 6042,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 55,
        "RLVL": 136,
        "STARS": 0,
        "CRAFTS": 539,
        "CONTROL": 502,
        "PROGRESS": 697,
        "QUALITY": 6301,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 56,
        "RLVL": 139,
        "STARS": 0,
        "CRAFTS": 550,
        "CONTROL": 513,
        "PROGRESS": 752,
        "QUALITY": 6561,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 57,
        "RLVL": 142,
        "STARS": 0,
        "CRAFTS": 560,
        "CONTROL": 524,
        "PROGRESS": 808,
        "QUALITY": 6820,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 58,
        "RLVL": 145,
        "STARS": 0,
        "CRAFTS": 570,
        "CONTROL": 535,
        "PROGRESS": 863,
        "QUALITY": 7080,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 59,
        "RLVL": 148,
        "STARS": 0,
        "CRAFTS": 580,
        "CONTROL": 546,
        "PROGRESS": 919,
        "QUALITY": 7339,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 60,
        "RLVL": 150,
        "STARS": 0,
        "CRAFTS": 587,
        "CONTROL": 553,
        "PROGRESS": 956,
        "QUALITY": 7851,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 60,
        "RLVL": 160,
        "STARS": 1,
        "CRAFTS": 620,
        "CONTROL": 589,
        "PROGRESS": 982,
        "QUALITY": 7874,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 60,
        "RLVL": 180,
        "STARS": 2,
        "CRAFTS": 718,
        "CONTROL": 695,
        "PROGRESS": 1033,
        "QUALITY": 8015,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 60,
        "RLVL": 210,
        "STARS": 3,
        "CRAFTS": 850,
        "CONTROL": 820,
        "PROGRESS": 1106,
        "QUALITY": 8298,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 60,
        "RLVL": 220,
        "STARS": 3,
        "CRAFTS": 870,
        "CONTROL": 835,
        "PROGRESS": 1234,
        "QUALITY": 8742,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 60,
        "RLVL": 250,
        "STARS": 4,
        "CRAFTS": 995,
        "CONTROL": 955,
        "PROGRESS": 1476,
        "QUALITY": 9230,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 61,
        "RLVL": 255,
        "STARS": 0,
        "CRAFTS": 1006,
        "CONTROL": 968,
        "PROGRESS": 1116,
        "QUALITY": 8377,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 62,
        "RLVL": 265,
        "STARS": 0,
        "CRAFTS": 1027,
        "CONTROL": 993,
        "PROGRESS": 1263,
        "QUALITY": 8581,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 63,
        "RLVL": 270,
        "STARS": 0,
        "CRAFTS": 1037,
        "CONTROL": 1005,
        "PROGRESS": 1476,
        "QUALITY": 9186,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 64,
        "RLVL": 273,
        "STARS": 0,
        "CRAFTS": 1044,
        "CONTROL": 1013,
        "PROGRESS": 1586,
        "QUALITY": 9657,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 65,
        "RLVL": 276,
        "STARS": 0,
        "CRAFTS": 1050,
        "CONTROL": 1020,
        "PROGRESS": 1697,
        "QUALITY": 10023,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 66,
        "RLVL": 279,
        "STARS": 0,
        "CRAFTS": 1056,
        "CONTROL": 1028,
        "PROGRESS": 1808,
        "QUALITY": 10389,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 67,
        "RLVL": 282,
        "STARS": 0,
        "CRAFTS": 1063,
        "CONTROL": 1035,
        "PROGRESS": 1919,
        "QUALITY": 10755,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 68,
        "RLVL": 285,
        "STARS": 0,
        "CRAFTS": 1069,
        "CONTROL": 1043,
        "PROGRESS": 2029,
        "QUALITY": 11121,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 69,
        "RLVL": 288,
        "STARS": 0,
        "CRAFTS": 1075,
        "CONTROL": 1050,
        "PROGRESS": 2140,
        "QUALITY": 11490,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 70,
        "RLVL": 290,
        "STARS": 0,
        "CRAFTS": 1079,
        "CONTROL": 1055,
        "PROGRESS": 2214,
        "QUALITY": 11736,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 70,
        "RLVL": 300,
        "STARS": 1,
        "CRAFTS": 1100,
        "CONTROL": 1080,
        "PROGRESS": 2361,
        "QUALITY": 11960,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 70,
        "RLVL": 320,
        "STARS": 2,
        "CRAFTS": 1320,
        "CONTROL": 1220,
        "PROGRESS": 2657,
        "QUALITY": 12511,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 70,
        "RLVL": 350,
        "STARS": 3,
        "CRAFTS": 1500,
        "CONTROL": 1350,
        "PROGRESS": 2760,
        "QUALITY": 13144,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 70,
        "RLVL": 380,
        "STARS": 4,
        "CRAFTS": 1650,
        "CONTROL": 1600,
        "PROGRESS": 2900,
        "QUALITY": 14267,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 71,
        "RLVL": 390,
        "STARS": 0,
        "CRAFTS": 1320,
        "CONTROL": 1220,
        "PROGRESS": 3149,
        "QUALITY": 13086,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 72,
        "RLVL": 395,
        "STARS": 0,
        "CRAFTS": 1388,
        "CONTROL": 1284,
        "PROGRESS": 3248,
        "QUALITY": 13660,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 73,
        "RLVL": 400,
        "STARS": 0,
        "CRAFTS": 1457,
        "CONTROL": 1348,
        "PROGRESS": 3348,
        "QUALITY": 14062,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 74,
        "RLVL": 403,
        "STARS": 0,
        "CRAFTS": 1498,
        "CONTROL": 1387,
        "PROGRESS": 3407,
        "QUALITY": 14482,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 75,
        "RLVL": 406,
        "STARS": 0,
        "CRAFTS": 1539,
        "CONTROL": 1425,
        "PROGRESS": 3467,
        "QUALITY": 14902,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 76,
        "RLVL": 409,
        "STARS": 0,
        "CRAFTS": 1580,
        "CONTROL": 1464,
        "PROGRESS": 3526,
        "QUALITY": 15322,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 77,
        "RLVL": 412,
        "STARS": 0,
        "CRAFTS": 1621,
        "CONTROL": 1502,
        "PROGRESS": 3586,
        "QUALITY": 15742,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 78,
        "RLVL": 415,
        "STARS": 0,
        "CRAFTS": 1662,
        "CONTROL": 1541,
        "PROGRESS": 3645,
        "QUALITY": 16162,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 79,
        "RLVL": 418,
        "STARS": 0,
        "CRAFTS": 1702,
        "CONTROL": 1579,
        "PROGRESS": 3705,
        "QUALITY": 16582,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 80,
        "RLVL": 430,
        "STARS": 0,
        "CRAFTS": 1866,
        "CONTROL": 1733,
        "PROGRESS": 3943,
        "QUALITY": 18262,
        "DURABILITY": 80,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 80,
        "RLVL": 440,
        "STARS": 1,
        "CRAFTS": 2000,
        "CONTROL": 1860,
        "PROGRESS": 4143,
        "QUALITY": 19662,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 80,
        "RLVL": 450,
        "STARS": 2,
        "CRAFTS": 2140,
        "CONTROL": 1990,
        "PROGRESS": 4343,
        "QUALITY": 23395,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 80,
        "RLVL": 480,
        "STARS": 3,
        "CRAFTS": 2480,
        "CONTROL": 2195,
        "PROGRESS": 4943,
        "QUALITY": 25863,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 80,
        "RLVL": 481,
        "STARS": 3,
        "CRAFTS": 2484,
        "CONTROL": 2206,
        "PROGRESS": 4963,
        "QUALITY": 25945,
        "DURABILITY": 70,
        "CONDITIONS": 115,
        "EXPERT": true
    },
    {
        "LEVEL": 80,
        "RLVL": 490,
        "STARS": 3,
        "CRAFTS": 2520,
        "CONTROL": 2305,
        "PROGRESS": 5143,
        "QUALITY": 26686,
        "DURABILITY": 70,
        "CONDITIONS": 15,
        "EXPERT": false
    },
    {
        "LEVEL": 80,
        "RLVL": 511,
        "STARS": 4,
        "CRAFTS": 2620,
        "CONTROL": 2540,
        "PROGRESS": 5563,
        "QUALITY": 28414,
        "DURABILITY": 70,
        "CONDITIONS": 115,
        "EXPERT": true
    },
    {
        "LEVEL": 80,
        "RLVL": 512,
        "STARS": 4,
        "CRAFTS": 2620,
        "CONTROL": 2540,
        "PROGRESS": 5583,
        "QUALITY": 28496,
        "DURABILITY": 70,
        "CONDITIONS": 115,
        "EXPERT": null
    },
    {
        "LEVEL": 80,
        "RLVL": 513,
        "STARS": 4,
        "CRAFTS": 2620,
        "CONTROL": 2540,
        "PROGRESS": 5603,
        "QUALITY": 28578,
        "DURABILITY": 70,
        "CONDITIONS": 483,
        "EXPERT": null
    },

    {
        "LEVEL": 80,
        "RLVL": 510,
        "STARS": 4,
        "CRAFTS": 2620,
        "CONTROL": 2540,
        "PROGRESS": 5820,
        "QUALITY": 46746,
        "DURABILITY": 35
    }
];

export default recipeLevel;