export enum Buff {
    MUSCLE_MEMORY = "MUSCLE_MEMORY", INNER_QUIET = "INNER_QUIET",
    WASTE_NOT = "WASTE_NOT", WASTE_NOT_II = "WASTE_NOT_II", MANIPULATION = "MANIPULATION",
    GREAT_STRIDES = "GREAT_STRIDES", VENERATION = "VENERATION", INNOVATION = "INNOVATION",
    FINAL_APPRAISAL = "FINAL_APPRAISAL"
}

export type Buffs = Record<Buff, number>